---
- name: Download Tomcat
  get_url: 
    url="{{tomcat_url}}"
    dest="{{download_dir}}/tomcat.tar.gz"

- name: Unpack sources
  unarchive: src="{{download_dir}}/tomcat.tar.gz" dest="{{download_dir}}"  copy=no

#- name: Unpack sources (cmd)
#  shell: " /bin/tar -xzf /tmp/tomcat.tar.gz "

- name: "Check if {{tomcat_dir}} exists"
  stat: path="{{tomcat_home}}"
  register: result

- name: Move to opt
  command: "mv {{download_dir}}/apache-tomcat-7.0.81 {{tomcat_home}}"
  when: (not result.stat.exists)

- name: Make files executable
  file: path={{tomcat_home}} mode=0755
  with_items: 
    - "{{tomcat_home}}/bin/startup.sh"
    - "{{tomcat_home}}/bin/shutdown.sh"
    - "{{tomcat_home}}/bin/catalina.sh"

- name: Allow ssh user to write to webapps dir
  file: path={{tomcat_home}}/webapps mode=0777
  with_items:
    - "{{tomcat_home}}/webapps/" 
